// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByBD1KQXaSZpGhCotJ3LR8kvQy84JyogM',
    appId: '1:625475597512:web:33f6aa0f3f333167b761fd',
    messagingSenderId: '625475597512',
    projectId: 'app-nghe-nhac-84db1',
    authDomain: 'app-nghe-nhac-84db1.firebaseapp.com',
    storageBucket: 'app-nghe-nhac-84db1.firebasestorage.app',
    measurementId: 'G-0T8RQH43XM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByeGvx3USGVJUJrqQgYjbB1gnN1undbrs',
    appId: '1:625475597512:android:4e65fb46d90731aab761fd',
    messagingSenderId: '625475597512',
    projectId: 'app-nghe-nhac-84db1',
    storageBucket: 'app-nghe-nhac-84db1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYILMI0Lk5K1scdVuEavZFxyorGsRE-PY',
    appId: '1:625475597512:ios:4deb7239d09813e0b761fd',
    messagingSenderId: '625475597512',
    projectId: 'app-nghe-nhac-84db1',
    storageBucket: 'app-nghe-nhac-84db1.firebasestorage.app',
    iosClientId: '625475597512-dgt2qbpiokhlanirkl0t06esmd7f1rq4.apps.googleusercontent.com',
    iosBundleId: 'com.example.test3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYILMI0Lk5K1scdVuEavZFxyorGsRE-PY',
    appId: '1:625475597512:ios:4deb7239d09813e0b761fd',
    messagingSenderId: '625475597512',
    projectId: 'app-nghe-nhac-84db1',
    storageBucket: 'app-nghe-nhac-84db1.firebasestorage.app',
    iosClientId: '625475597512-dgt2qbpiokhlanirkl0t06esmd7f1rq4.apps.googleusercontent.com',
    iosBundleId: 'com.example.test3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByBD1KQXaSZpGhCotJ3LR8kvQy84JyogM',
    appId: '1:625475597512:web:a5978fdddddbdfbbb761fd',
    messagingSenderId: '625475597512',
    projectId: 'app-nghe-nhac-84db1',
    authDomain: 'app-nghe-nhac-84db1.firebaseapp.com',
    storageBucket: 'app-nghe-nhac-84db1.firebasestorage.app',
    measurementId: 'G-ZD3BMLJKPB',
  );
}
